language: ruby
rvm:
- jruby-1.7.20
before_install:
- gem install bundler -v 1.10.1
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: ZFdsmBGEC8M+ptjhs3VQWf1n+ov5sZfMMGqQctcppZtHnrlrGYd6lwt/NxeyfqsXEklK+h/ykTP+2aCTul0DdjbPfxSYNcnOrDnealX08WRumbVpAdsfCkeLcpvTNr9MHv0DT74LA1DR1oCBspy46jelf75T7+PZLk2/XrmaHOT5nIKRHx61Ic6cU7YFJSM/sJm/C6Y3hfEqBzj1tH5EBZ4YLxCRScR2ExJDdXeShPjhVgdse+2mLzVSPvorvcztUd9KzfM8W5RzMFB3MJFBZRhAqAQgmiI7ceyss0KE5IUgwg5sgETvMby7WQ/DdMrRJpSSK5rG8cN38MQOlsz2S4QiLG9Sd6tKV3KOuiuy08b6EwrqStKXDYVDS73STAnHIpoAFsWqGRQhFNqXK64A729uthzRQTpESNzl8pjD12zfzfqfHn1BzD2X/ywzwcaOPzYGF2B7/5/TbgAFd39XxXd01AWFFlBqyzkSuPQjU7mlWmcbGF+Y/2UDmpkR6hfaXGQdg2Z87vFF6+Wmjk7lzCzaQeWmECgP+Pw3NYz9JMAPnYNiYWeVYQWZidUHaWWUTaFrEc6QpwQNO9xQajcmxJEOEk6vTkyfFZGmWneMd7nxYZ7vOn0PkerbjLkWHsKAztY8VUR6erUOG1lPxyNA2KjZ7bxa4LS1A2Yj5MGW32c=
after_success:
- coveralls
addons:
  code_climate:
    repo_token:
      secure: bHBQO01SKDgd+FB8hfwoGsPnXL+a6orf3rzXmcF8E71WRDGXgj/Qu+U3kyRR0AIFAXhBz2+RrMnBRmqiRpinWWpxFyA9RmSjRMHP5fAKukHZu9u1AyY+3M+/cR5AEwiGxvd6rzaYffw9Qn5WSTqkAmz8PrMLwkBn4Wc90nX6WAaasx4p28IIalqHo8ETWMbs7Tb1442bsDUrUzC3dA4NTcil5Z5uLvtX75fJe0k/tgp7XuUkGbUg+v+cFbjdVsTu8ZEp6gpChmBD91OxW5t9n+nVeXR8wyZp0TxbP47Tn7BMU3qAv08fc+SuqJE0XFm1eI9Z9Fu4WrWMS5IIvcXeFqIl3rHRD84T2UIeLaLvjDjYmwvhGYIZ5LO9SzKA/qefOXp/drvvDX98GDnlCrFAXiKyHmZPHWp9zJU+RXjhTT1HmvOgHbi+xglqjFEdSuR2XjxGxoDukTEVSb7gUKOhmvNWA12YJRv+HEM4dYYVYDQrnrWz37QRaS/aLERuL4d+Y+0gRTPi3FRjnBGeEYBVLNHRSB3SvjOUWsCobTFNhRN32w1Pkdk9DrPXfG9hD4jcOhL6G2Q/URkR3TAAhEuXjkmXrxt6CqQoOFM/yGpTQ4BNBfTis9WGzsAFGowVYVUoEJsaRcgzuFcbqv2W+bAc4j4JSsRPw6pf7mItjlRwClY=
cache: bundler
